import type { Metadata } from "next";
import { Space_Grotesk, Roboto, Lexend } from "next/font/google";
import "./globals.css";
import Wrapper from "@/components/wrapper/wrapper";
import Navigation from "@/components/navigation/navigation";
import { Footer11 } from "@/components/footer/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  weight: ["400", "700"],
  subsets: ["latin"],
});

const lexend = Lexend({
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["500"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lexend.className}>
        <Wrapper>
          <Navigation />
        </Wrapper>
        {children}
        <Footer11 />
      </body>
    </html>
  );
}
